export const af = [
    "Growth is not always visible, but it’s always happening.",
    "Rest is not a waste of time.",
    "Even the smallest step forward still counts.",
    "Healing is not linear.",
    "A pause can be powerful.",
    "Storms pass. Clarity follows.",
    "Progress often looks like repetition.",
    "Light returns, even after the darkest night.",
    "Peace grows slowly but steadily.",
    "Some days, breathing is enough.",
    "The journey matters as much as the destination.",
    "Silence can be a kind of strength.",
    "Slow moments hold deep value.",
    "Not all progress needs to be seen to be real.",
    "Softness is not weakness.",
    "Consistency beats intensity.",
    "It’s okay for the answer to be “not yet.”",
    "Gentle beginnings lead to strong roots.",
    "Clarity often follows confusion.",
    "Stillness has its own kind of wisdom.",
    "Small joys build strong foundations.",
    "Kindness leaves a lasting imprint.",
    "Effort matters, even without perfection.",
    "Letting go creates space for something new.",
    "New chapters often start quietly.",
    "There is wisdom in taking a breath.",
    "Calm is contagious.",
    "The sun always rises again.",
    "Space is sacred.",
    "There is beauty in becoming.",
    "Holding on and letting go both take courage.",
    "Foundations are built slowly.",
    "Energy flows where attention goes.",
    "It’s okay to take the long way.",
    "Still waters run deep.",
    "Some things bloom later — and better.",
    "Gentle beginnings often lead to powerful ends.",
    "A seed doesn't need to know it’s a forest yet.",
    "Quiet effort often makes the loudest impact.",
    "Balance is a moving target — not a fixed state.",
   "Trust grows over time, not overnight.",
    "The process is the point.",
    "The view changes as the path unfolds.",
    "Everything has a reason.",
    "Roots grow before blossoms show.",
    "Peace doesn't shout — it whispers.",
    "Gentle focus brings lasting results.",
    "Not everything needs to be rushed.",
    "Presence is more powerful than perfection.",
    "Becoming is its own kind of arrival."
]

export const tl = [
    "Discipline doesn't care about motivation.",
    "Nobody’s coming — show up for yourself.",
    "Action beats anxiety. Every. Single. Time.",
    "Get up. You’ve wasted enough time already.",
    "It's hard — do it anyway.",
    "Waiting to “feel like it” is a trap.",
    "Excuses don’t pay off — effort does.",
    "Future comfort is built on present discomfort.",
    "Don’t confuse being busy with being effective.",
    "You’re not tired — you’re distracted.",
    "Perfect is the enemy of done.",
    "Comfort is addictive. Fight it.",
    "Growth starts where comfort ends.",
    "You're allowed to rest — but not to quit.",
    "Stop scrolling. Start doing.",
    "This moment won’t come back.",
    "Time is not waiting for clarity. Move.",
    "You wanted this. So act like it.",
    "You can do hard things — prove it.",
    "Finish what you start.",
    "Get serious or get left behind.",
    "You don't need a plan. You need action.",
    "No one’s watching. Win anyway.",
    "Fight the urge to escape.",
    "The dream won’t chase itself.",
    "Being overwhelmed isn’t an excuse.",
    "Choose progress over pity.",
    "Do it ugly. Do it tired. But do it.",
    "The time you’re wasting adds up.",
    "You’re not late — you’re just avoiding.",
    "You owe it to yourself to try harder.",
    "Procrastination is self-sabotage in disguise.",
    "Hustle now, coast later.",
    "You're not behind — you’re not consistent.",
    "You don't need more time. You need less hesitation.",
    "This is your wake-up call.",
    "You already know what to do.",
    "If it matters, it gets done.",
    "One hour a day is still seven a week.",
    "Show your future self some respect.",
    "You said you’d do it. So go.",
    "Focus. Execute. Repeat.",
    "Stop romanticizing the struggle and fix it.",
    "You can either suffer now or regret later.",
    "Nobody owes you momentum — build it.",
    "Fear won’t leave — do it scared.",
    "Every excuse steals a win from you.",
    "If you're tired of starting over, stop quitting.",
    "You can chill after you’ve done your part.",
    "Work until it's no longer about proving anything."
]

export const ff = [
    "Octopuses have three hearts and blue blood.",
    "Bananas are technically berries.",
    "Wombat poop is cube-shaped.",
    "Honey never spoils.",
    "The Eiffel Tower grows taller in summer.",
    "Cows have best friends and get stressed when separated.",
    "A snail can sleep for three years.",
    "Butterflies can taste with their feet.",
    "The inventor of the microwave received only $2 for his idea.",
    "Pineapples take two years to grow.",
    "A cloud can weigh over a million pounds.",
    "There are more fake flamingos in the world than real ones.",
    "The dot over a lowercase ‘i’ is called a “tittle.”",
    "There are more stars in the universe than grains of sand on Earth.",
    "Otters hold hands while sleeping so they don’t drift apart.",
    "Some turtles can breathe through their butts.",
    "Cheetahs can't roar — they meow like house cats.",
    "A group of flamingos is called a flamboyance.",
    "Sloths can hold their breath longer than dolphins.",
    "It rains diamonds on Jupiter and Saturn.",
    "Seahorses mate for life and the males carry the babies.",
    "Pigeons can recognize themselves in mirrors.",
    "The longest hiccup spree lasted 68 years.",
    "Sharks existed before trees.",
    "Kangaroos can’t walk backward.",
    "The heart of a blue whale is the size of a small car.",
    "The world’s smallest reptile fits on a fingertip.",
    "Jellyfish don’t have brains.",
    "Tomatoes were once considered poisonous in Europe.",
    "A day on Venus is longer than its year.",
    "Goldfish can recognize human faces.",
    "Most dust in homes is made of dead skin.",
    "The first oranges weren’t orange — they were green.",
    "Ice pops were invented by an 11-year-old.",
    "Elephants are the only mammals that can’t jump.",
    "Spiders can’t fly, but some can glide through the air.",
    "There’s a planet made entirely of ice — that’s on fire.",
    "Mice can sing to each other in ultrasonic frequencies.",
    "The smell of freshly-cut grass is actually a plant distress call.",
    "Rabbits can’t vomit.",
    "A shrimp's heart is in its head.",
    "Cats only meow to humans — not to each other.",
    "An ant can survive a fall from any height.",
    "The moon has moonquakes.",
    "Blue eyes actually lack blue pigment.",
    "Some mushrooms glow in the dark.",
    "Water can boil and freeze at the same time (triple point).",
    "Koalas have fingerprints almost identical to humans.",
    "The word “unfriend” dates back to 1659.",
    "Penguins propose with pebbles."
]

export const pred = [
    "Something unexpectedly good is coming your way.",
    "A moment of calm will surprise you today.",
    "A tiny win will spark a big shift.",
    "You'll smile for no reason — and it'll feel right.",
    "A weight you didn’t know you were carrying will lift.",
    "Peace will come from somewhere strange.",
    "Today will teach something worth keeping.",
    "A compliment is headed toward you.",
    "You’ll solve something you've been stuck on.",
    "The right words will reach you when you need them.",
    "A problem will seem smaller by tomorrow.",
    "An answer is closer than you think.",
    "New energy is brewing in the background.",
    "A person you admire will see your effort.",
    "Clarity is just a pause away.",
    "A task will be easier than expected.",
    "A gentle surprise will restore your faith in the day.",
    "Today holds something quietly magical.",
    "A little courage will change everything.",
    "Something you’ve been avoiding will feel doable soon.",
    "A door will open without force.",
    "Something long overdue will finally begin.",
    "A simple joy will feel deeper than usual.",
    "This week will hold something unforgettable.",
    "A new routine will click into place.",
    "A tiny spark will lead to momentum.",
    "Something old will finally make sense.",
    "A moment alone will feel healing instead of lonely.",
    "A message will arrive exactly when needed.",
    "Your ideas will find the right ears.",
    "There’s ease waiting on the other side of effort.",
    "A daydream will feel a little more possible.",
    "There will be warmth from an unexpected source.",
    "Something lost will return — in a new way.",
    "Stillness will bring clarity today.",
    "Something you planted is quietly growing.",
    "You’ll laugh more than you expect.",
    "Energy will return just when you need it.",
    "You’ll make someone’s day — even without knowing.",
    "A question will answer itself.",
    "Gratitude will sneak in quietly.",
    "Something you feared won’t happen.",
    "Someone’s thinking of you — and it matters.",
    "There’s a surprise waiting in your own strength.",
    "You’ll look back and be proud of today.",
    "There’s more softness ahead than you imagined.",
    "A quiet “yes” is coming.",
    "A project will find new life.",
    "Joy will come disguised as something small.",
    "You’re closer than you think."
]